- README.md
- docs/index.html
- lib/index.mjs
* Give each token type names
* Add `;` to sign tokens
> Add type names

- docs/main.js
- lib/index.mjs
> Fix: inline jsx attributes parsing

- docs/main.js
- lib/index.mjs
> Fix jsx literals

- docs/main.js
Fix textarea don't expand when adding new line to the bottom. PM me if my English confused you :)
---
How to reproduce:
1. Scroll down to the bottom on https://sugar-high.vercel.app/
2. Press "return" key to see the result
> Fix textarea don't expand

- .github/workflows/test.yml
- lib/index.mjs
- package.json
- test/ast.test.js
* treaet jsx inline literals as text
* add test runner and some basic tests
> feat: treaet jsx inline literals as text

- lib/index.mjs
- test/ast.test.js
> feat: consider regex flags as part of it

- lib/index.mjs
- test/ast.test.js
> Fix: pair the quotes of string

- lib/index.mjs
- test/ast.test.js
* treat `@` as sign
* collect existing token before entering comment
> Fix missing char with comment and add @ as sign

- README.md
- docs/pages/index.js
- lib/index.mjs
> feature: support line number

- README.md
- docs/pages/index.js
- lib/index.mjs
- test/ast.test.js
> fix: matching jsx tags

- README.md
- docs/pages/index.js
- lib/index.mjs
* use css counter to implement line number
* support overflow inline text
> enhance: remove data-line-number use css counter to implment line number

- docs/pages/index.js
- package.json
- yarn.lock
> docs: scrollable view

- lib/index.mjs
- test/ast.test.js
> fix: parse arrow function in jsx

- docs/pages/index.js
- lib/index.mjs
- test/ast.test.js
> feat: support unicode

- docs/app/layout.jsx
- docs/app/page.jsx
- docs/app/styles.css
* Use carousel to demo code snippets
* Add github link
> refine website

- test/ast.test.js
Closes https://github.com/huozhi/sugar-high/issues/71
Hi, I'm sharing progress to get early feedback.
> refactor: add utility to format test results into array

- docs/app/live-editor.js
- lib/index.mjs
- test/ast.test.js
> fix: jsx state for self close tag

- package.json
> types: add types field in package.json

- docs/app/live-editor.js
Close #79 
https://github.com/huozhi/sugar-high/assets/11806619/1f7a8fb1-1a11-4e7b-96e8-2a32370ea63b
> website(feat): save user input into LocalStorage

- package.json
> types: add types field for node module resolving in ts

- docs/app/carousel.js
- docs/app/components/install-banner.css
- docs/app/components/install-banner.js
- docs/app/styles.css
> docs: highlight line

- lib/index.js
- test/ast.test.js
> fix: tailwind prop with equal sigh

- README.md
Hey Jiachi, 
thank you for your work @vercel & for this packacke. I found it to be very useful while rebuilding my website. I think I found a spelling & css prefix mistake in your ReadMe and changed it.
Have a nice day,
Merlin
> fix: spelling & css prefix

- docs/app/editor/page.js
- docs/app/live-editor.js
- lib/index.js
- test/ast.test.js
> fix: jsx prop with break line

- docs/app/editor/page.js
- lib/index.js
- test/ast.test.js
> fix: handle angle brackets in string or regex

- lib/index.d.ts
- lib/index.js
- test/tokenize.test.ts
add new option `onCommentStart` to mark when new comment is started
> feat: add option of onCommentStart

- lib/index.d.ts
- lib/index.js
- package.json
- pnpm-lock.yaml
- test/tokenize.test.ts
Add `onCommentEnd ` to match inline and block comments
> fix: match onCommentEnd

- lib/index.js
- test/ast.test.ts
> fix: comment type matching

- lib/index.js
- test/ast.test.ts
- test/testing-utils.ts
> fix: missing space in jsx prop

- lib/index.js
return more structural data in `generate` API
> improve node props

- lib/index.js
- test/ast.test.ts
Fix the previous #118 properly, the space was lost
> fix missing spaces in jsx
